# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CGNY' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CGNY

  target 'CGNYTests' do
    inherit! :search_paths
    pod 'OCMock', '~>3.1.5'
  end

end
